version: '3.8'

services:
  db:
    image: postgres:15
    container_name: easydeploy_db
    environment:
      POSTGRES_DB: easydeploy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d easydeploy"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  web:
    build: .
    container_name: easydeploy_web
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8000"  # use host 8080 to avoid Nginx port 80 conflict
    volumes:
      - staticfiles:/app/staticfiles
      - media:/app/media
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ec2-user/main-app2/EasyDeploy:/app/ssh:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      GITHUB_CLIENT_ID: "Ov23liDBqBoJA5motUgG"
      GITHUB_CLIENT_SECRET: "100d4a956460db2e54ac8bc0980dcdfe40eafb18"
      GITHUB_REDIRECT_URI: "http://launchhub-alb-1333351530.us-east-1.elb.amazonaws.com/github/callback/"
      PUBLIC_BASE_URL: "http://launchhub-alb-1333351530.us-east-1.elb.amazonaws.com"
      PUBLIC_BASE_INCLUDE_PORT: "false"
      # RDS database connection (override local db)
      DB_NAME: "easydeploy"
      DB_USER: "postgres"
      DB_PASSWORD: "Minimax999157"
      DB_HOST: "database-1.c728eaaievd3.us-east-1.rds.amazonaws.com"
      DB_PORT: "5432"
      DB_SSLMODE: "require"
      # Remote SSH deploy (deploy to both EC2s; app auto-skips self)
      REMOTE_DEPLOY_HOSTS: "10.0.140.245,10.0.153.76"
      LOCAL_HOST_IP: "${LOCAL_HOST_IP}"
      REMOTE_DEPLOY_SSH_USER: "ec2-user"
      REMOTE_DEPLOY_SSH_KEY_PATH: "/app/ssh/backend-key.pem"
    command: >
      bash -lc "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped

volumes:
  pgdata:
  staticfiles:
  media: