version: '3.8'

services:
  db:
    image: postgres:15
    container_name: easydeploy_db
    environment:
      POSTGRES_DB: easydeploy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d easydeploy"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  web:
    build: .
    container_name: easydeploy_web
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8000"  # use host 8080 to avoid Nginx port 80 conflict
    volumes:
      - staticfiles:/app/staticfiles
      - media:/app/media
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      GITHUB_CLIENT_ID: "Ov23liDBqBoJA5motUgG"
      GITHUB_CLIENT_SECRET: "100d4a956460db2e54ac8bc0980dcdfe40eafb18"
      GITHUB_REDIRECT_URI: "http://100.25.10.212/github/callback/"
      # RDS database connection (override local db)
      DB_NAME: "easydeploy"
      DB_USER: "postgres"
      DB_PASSWORD: "Minimax999157"
      DB_HOST: "database-1.c728eaaievd3.us-east-1.rds.amazonaws.com"
      DB_PORT: "5432"
      DB_SSLMODE: "require"
    command: >
      bash -lc "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped

volumes:
  pgdata:
  staticfiles:
  media: